### ISSUE TITLE
Arrays: serialization does not match schema

### ISSUE THREAD

**Issue by mcf-rocks** [near/borsh#114]
I think this line: 
https://github.com/near/borsh/blob/50c3c5d4618067546ecc5bace7031cb5566e189d/borsh-rs/borsh/src/schema.rs#L162

Should be changed to be the same as this line:
https://github.com/near/borsh/blob/50c3c5d4618067546ecc5bace7031cb5566e189d/borsh-rs/borsh/src/ser/mod.rs#L347

but with the addition of ‘0’ as the first element as per the schema line.

**Comment by austinabell** [comment]
Closing based on your PR https://github.com/near/borsh-rs/pull/22
