### ISSUE TITLE
Error: Expected buffer length 1207959552 isn't within bounds: buyer

### ISSUE THREAD

**Issue by AndonMitev** [near/borsh#117]
When i try to deserialize my buffer on which the length is 173 i get this error:

`(node:60078) UnhandledPromiseRejectionWarning: Error: Expected buffer length 1207959552 isn't within bounds: buyer`

**Comment by TheGrado** [comment]
How did you solve this?

**Comment by singulart** [comment]
@AndonMitev Can you please advise how to fix this problem? Facing it myself :)

**Comment by 0xSavant** [comment]
was this ever resolved?

**Comment by acuna-public** [comment]
Problem is that you're using wrong schema to deserialize, for example Metadata using `Metadata::SCHEMA`, Account using `Account::SCHEMA` etc. Schema is a struct of a fields you need to get in your deserialized string. I'm using another library for another language, so I can only give you a glue.
