### ISSUE TITLE
Check whether replacing Read with slice or using byteorder, or both speeds us up

### ISSUE THREAD

**Issue by nearmax** [near/borsh#29]
We should also address https://github.com/nearprotocol/borsh/issues/26 . The change that I did to array was very suboptimal.

**Comment by fckt** [comment]
btw, `byteorder` is doing basically the same thing: creates a byte array and copy data from slice.
https://docs.rs/byteorder/1.1.0/src/byteorder/lib.rs.html#1705

**Comment by nearmax** [comment]
I actually see the opposite -- that they do not create an intermediate array.
Suppose we are reading `u32` from a slice using `LittleEndian :: read_u32 ` https://docs.rs/byteorder/1.1.0/src/byteorder/lib.rs.html#1986
`read_num_bytes` creates `let mut data: u32 = 0;` and then writes bytes directly into it using `copy_nonoverlapping`. It then returns `u32` using `data. to_le()` which is a no-op on LE machines.

What we currently do makes one more allocation:
* First, we create an array: https://github.com/nearprotocol/borsh/blob/master/borsh-rs/borsh/src/de/mod.rs#L41
* Then we write data into the array.
* Finally, we create an actual variable of the desired type by calling `u32::from_le_bytes(data)`.

That's two allocations: array and the variable. Besides, `copy_nonoverlapping` is a `memcpy` so it should be fast.

**Comment by fckt** [comment]
What I see:
`from_le_bytes` calls `from_ne_bytes` https://doc.rust-lang.org/src/core/num/mod.rs.html#2098 it uses `transmute` which does `memcpy` either.. 

With `byteorder` we have to allocate an array too, since the slice we pass as input have to be the same length as a value we are trying to convert to.. In `byteorder` they doing the same thing: https://docs.rs/byteorder/1.3.2/src/byteorder/io.rs.html#214

**Comment by nearmax** [comment]
> With byteorder we have to allocate an array too, since the slice we pass as input have to be the same length as a value we are trying to convert to.. In byteorder they doing the same thing: https://docs.rs/byteorder/1.3.2/src/byteorder/io.rs.html#214

Yes, it looks like byteorder does not give an advantage if we read from `T: Read`. byteorder provides read/write implementation for various use-cases. The link that I've posted above: https://docs.rs/byteorder/1.1.0/src/byteorder/lib.rs.html#1986 is for slices. The link that you've posted is for `T: Read` https://docs.rs/byteorder/1.3.2/src/byteorder/io.rs.html#214 . So, what we should do is use byteorder with slice.

**Comment by fckt** [comment]
I've experimented on changing from Read to just using a slice interface - the performance is the same. See https://github.com/near/borsh/blob/fckt/read-to-slice2/borsh-rs/borsh/src/de/mod.rs

Closing it since there is no progress expected on the issue.
