### ISSUE TITLE
`try_to_vec` never returns Result::Err()

### ISSUE THREAD

**Issue by fckt** [near/borsh#59]
Since the writer is vector, it will never return `Result::Err()`. Since that we're able to not return an `Result`. We use the interface quite often everywhere. Right now code is bloated with unnecessary `unwrap()`s.

`try_to_vec` https://github.com/nearprotocol/borsh/blob/af0e6d87142559150dc86e14c6f469cc40c8909e/borsh-rs/borsh/src/ser/mod.rs#L11

A Vec Write implementation:
https://doc.rust-lang.org/src/std/io/impls.rs.html#339

What do you think @nearmax ?

**Comment by nearmax** [comment]
It returns error to allow custom types that have their own implementation of BorshSerialize to return error if something goes wrong. E.g. if type has inconsistent internal state that it refuses to serialize.

Closing as WAI.

**Comment by fckt** [comment]
```rust
use std::io::{Error, Write};
fn try_to_vec(&self) -> Result<Vec<u8>, Error>
```
Where Error is an input/output error. Copy to vector cannot return input/output Error.

We can just add `fn to_vec() -> Vec<u8>`

**Comment by nearmax** [comment]
> In that case the interface should allow to specify a custom error type. 

`io::Error` is widely used by Rust serializers, it should be sufficient for custom-written serialization methods too.
