### ISSUE TITLE
Implement serialization for std::borrow::Cow

### ISSUE THREAD

**Issue by frol** [near/borsh#74]
How hard would it be to implement [Cow](https://doc.rust-lang.org/stable/std/borrow/enum.Cow.html) support?

When you deserialize, you just always use the Owned variant, otherwise, you only need `as_ref()` to read the data.

/cc @nearmax

**Comment by evgenykuzyakov** [comment]
Can you give an example?

**Comment by frol** [comment]
```rust
#[derive(
    BorshSerialize,
    BorshDeserialize,
)]
pub struct AccountId<'a>(std::borrow::Cow<'a, str>);
```

**Comment by evgenykuzyakov** [comment]
Well, it shouldn't be an issue I guess

**Comment by frol** [comment]
Cool thanks! I will take a look from here.
