### ISSUE TITLE
Derive failure for `&[T]`

### ISSUE THREAD

**Issue by bowenwang1996** [near/borsh#97]
If I have the following structs
```rust
#[derive(BorshSerialize]
struct A {}
#[derive(BorshSerialize)]
struct B<'a> {
  a: &'a [A]
}
```
The derive for `B` will fail even though we have derive for `[T]` and `&T` if `T` implements `BorshSerialize`. It fails with "size for value cannot be known at compile time. If I change `[A]` to `Vec<A>`, it works.

**Comment by evgenykuzyakov** [comment]
I think BorshSerialize requires `Sized`, but we probably can lift this requirement. You still need it for `BorshDeserialize`
